server:
  port: ":3000"
auth:
  api_key: "inohom-api-key"
  api_value: "WdBWZnG7-93q9bgEIDJNCgyJROrqHdOgHN19_heY94w"
internal_log:
  log_file: "./server.log"
kettas_log:
  upload_dir: "./temp_uploads"
  logs_dir: "./kettas-logs"
  zip_password: "!tekniklog64"
  max_file_size: 52428800 # 50MB
